# Generated by Django 5.0.2 on 2024-12-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=100)),
                ('core_no', models.CharField(max_length=50)),
                ('depth_md', models.FloatField(blank=True, null=True)),
                ('depth_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('porosity', models.FloatField(blank=True, null=True)),
                ('perm_kair', models.FloatField(blank=True, null=True)),
                ('grain_density', models.FloatField(blank=True, null=True)),
                ('resistivity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
