# Generated by Django 5.0.2 on 2024-12-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_no', models.IntegerField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='core_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='welldata',
            name='core_no',
        ),
        migrations.AlterField(
            model_name='welldata',
            name='depth_interval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='welldata',
            name='core',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='well_data', to='plotter.core'),
            preserve_default=False,
        ),
    ]
