# Generated by Django 5.0.2 on 2024-12-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_core_remove_welldata_core_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welldata',
            name='core_no',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='welldata',
            name='core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welldata_set', to='plotter.core'),
        ),
        migrations.AlterField(
            model_name='welldata',
            name='depth_interval',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
