# Generated by Django 5.0.2 on 2024-12-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0004_alter_core_core_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welldata',
            name='depth_interval',
        ),
        migrations.RemoveField(
            model_name='welldata',
            name='depth_md',
        ),
    ]
