# Generated by Django 5.0.2 on 2024-12-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0005_remove_welldata_depth_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welldata',
            name='core_no',
            field=models.IntegerField(),
        ),
    ]
