# Generated by Django 5.0.2 on 2024-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0006_alter_welldata_core_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='well_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='core',
            unique_together={('well_name', 'core_no')},
        ),
    ]
