# Generated by Django 5.0.2 on 2025-02-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0007_core_well_name_alter_core_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, help_text='Area in square kilometers', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('gas_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='plotter.gasfield')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow_rate', models.FloatField()),
                ('cumulative_flow_rate', models.FloatField()),
                ('water_production', models.FloatField()),
                ('condensate_production', models.FloatField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='plotter.well')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('well', 'date')},
            },
        ),
    ]
