# Generated by Django 5.0.2 on 2025-02-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0008_gasfield_well_productiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='litho_image',
            field=models.ImageField(blank=True, null=True, upload_to='litho_images/'),
        ),
    ]
