# Generated by Django 5.0.2 on 2025-03-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0009_core_litho_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
