# Generated by Django 5.0.2 on 2025-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0011_explorationcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Operation Activity',
                'verbose_name_plural': 'Operation Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
