# Generated by Django 5.0.2 on 2025-09-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0013_alter_welldata_options_fossils_mineralogy_grainsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welldata',
            options={},
        ),
    ]
