# Generated by Django 5.0.2 on 2025-09-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0014_alter_welldata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welldata',
            options={'verbose_name': 'Petro Analysis', 'verbose_name_plural': 'Petro Analyses'},
        ),
    ]
