# Generated by Django 5.0.2 on 2025-11-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0015_alter_welldata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDrillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depth', models.FloatField(help_text='Current depth in meters')),
                ('current_operation', models.CharField(max_length=255)),
                ('shale_percentage', models.FloatField(default=0, help_text='Percentage of shale')),
                ('sand_percentage', models.FloatField(default=0, help_text='Percentage of sand')),
                ('clay_percentage', models.FloatField(default=0, help_text='Percentage of clay')),
                ('silk_percentage', models.FloatField(default=0, help_text='Percentage of silk')),
                ('gas_show', models.TextField(blank=True, help_text='Description of gas shows if any', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drilling_reports', to='plotter.well')),
            ],
            options={
                'verbose_name': 'Daily Drilling Report',
                'verbose_name_plural': 'Daily Drilling Reports',
                'ordering': ['date', 'depth'],
            },
        ),
    ]
