# Generated by Django 5.0.2 on 2025-11-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0016_dailydrillingreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydrillingreport',
            options={'ordering': ['date', 'depth_start'], 'verbose_name': 'Daily Drilling Report', 'verbose_name_plural': 'Daily Drilling Reports'},
        ),
        migrations.RemoveField(
            model_name='dailydrillingreport',
            name='depth',
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='depth_end',
            field=models.FloatField(default=1, help_text='end depth in meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='depth_start',
            field=models.FloatField(default=1, help_text='start depth in meters'),
            preserve_default=False,
        ),
    ]
