# Generated by Django 5.0.2 on 2025-11-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0017_alter_dailydrillingreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='current_operation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
