# Generated by Django 5.0.2 on 2025-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0018_alter_dailydrillingreport_current_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydrillingreport',
            old_name='silk_percentage',
            new_name='slit_percentage',
        ),
    ]
