# Generated by Django 5.0.2 on 2025-11-02 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0019_rename_silk_percentage_dailydrillingreport_slit_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydrillingreport',
            name='clay_percentage',
        ),
        migrations.RemoveField(
            model_name='dailydrillingreport',
            name='sand_percentage',
        ),
        migrations.RemoveField(
            model_name='dailydrillingreport',
            name='shale_percentage',
        ),
        migrations.RemoveField(
            model_name='dailydrillingreport',
            name='slit_percentage',
        ),
        migrations.CreateModel(
            name='DrillingLithology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.FloatField(help_text='Start depth in meters')),
                ('depth_to', models.FloatField(help_text='End depth in meters')),
                ('shale_percentage', models.FloatField(default=0, help_text='Percentage of shale')),
                ('sand_percentage', models.FloatField(default=0, help_text='Percentage of sand')),
                ('clay_percentage', models.FloatField(default=0, help_text='Percentage of clay')),
                ('slit_percentage', models.FloatField(default=0, help_text='Percentage of slit')),
                ('description', models.TextField(blank=True, null=True)),
                ('drilling_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lithologies', to='plotter.dailydrillingreport')),
            ],
            options={
                'verbose_name': 'Drilling Lithology',
                'verbose_name_plural': 'Drilling Lithologies',
                'ordering': ['depth_from'],
            },
        ),
    ]
