# Generated by Django 5.0.2 on 2025-11-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0020_remove_dailydrillingreport_clay_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydrillingreport',
            name='csg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='depth_end_tvd',
            field=models.FloatField(blank=True, help_text='end depth (TVD) in meters', null=True),
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='depth_start_tvd',
            field=models.FloatField(blank=True, help_text='start depth (TVD) in meters', null=True),
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='last_csg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='next_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='present_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydrillingreport',
            name='report_no',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='rig',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='spud_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='depth_end',
            field=models.FloatField(help_text='end depth (MD) in meters'),
        ),
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='depth_start',
            field=models.FloatField(help_text='start depth (MD) in meters'),
        ),
    ]
