# Generated by Django 5.0.2 on 2025-11-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0021_dailydrillingreport_csg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellPrognosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_depth_start', models.DecimalField(decimal_places=2, help_text='Planned start depth (m)', max_digits=10)),
                ('planned_depth_end', models.DecimalField(decimal_places=2, help_text='Planned end depth (m)', max_digits=10)),
                ('lithology', models.CharField(choices=[('sand', 'sand'), ('lime', 'lime'), ('shale', 'shale'), ('slit', 'slit'), ('dolomite', 'dolomite'), ('coal', 'coal')], help_text='Expected lithology at this depth', max_length=50)),
                ('target_depth', models.BooleanField(default=False, help_text='Is this a target depth?')),
                ('casing_size', models.CharField(blank=True, max_length=50, null=True)),
                ('drilling_fluid', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prognoses', to='plotter.well')),
            ],
            options={
                'ordering': ['planned_depth_start'],
            },
        ),
    ]
