# Generated by Django 5.0.2 on 2025-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0022_wellprognosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='report_no',
            field=models.IntegerField(),
        ),
    ]
