# Generated by Django 5.0.2 on 2025-11-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0023_alter_dailydrillingreport_report_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='report_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wellprognosis',
            name='lithology',
            field=models.CharField(choices=[('sand', 'sand'), ('lime', 'lime'), ('shale', 'shale'), ('slit', 'slit'), ('dolomite', 'dolomite'), ('coal', 'coal'), ('clay', 'clay')], help_text='Expected lithology at this depth', max_length=50),
        ),
    ]
