# Generated by Django 5.0.2 on 2025-11-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0024_alter_dailydrillingreport_report_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BHAComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bit', 'Drill Bit'), ('stabilizer', 'Stabilizer'), ('drill_collar', 'Drill Collar'), ('heavy_weight', 'Heavy Weight Drill Pipe'), ('drill_pipe', 'Drill Pipe'), ('jar', 'Jar'), ('mwd', 'MWD Tool'), ('motor', 'Downhole Motor'), ('reamer', 'Reamer'), ('cross_over', 'Cross-over Sub'), ('other', 'Other')], max_length=50)),
                ('length', models.FloatField(help_text='Length in meters')),
                ('outer_diameter', models.FloatField(help_text='Outer diameter in inches')),
                ('inner_diameter', models.FloatField(blank=True, help_text='Inner diameter in inches', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('connection_type', models.CharField(blank=True, help_text='Type of thread connection', max_length=50, null=True)),
                ('svg_template', models.TextField(help_text='SVG template for component visualization')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_length', models.FloatField(blank=True, help_text='Total length in meters', null=True)),
                ('total_weight', models.FloatField(blank=True, help_text='Total weight in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drilling_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bha_configurations', to='plotter.dailydrillingreport')),
            ],
        ),
        migrations.CreateModel(
            name='BHAComponentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position from bottom up (1 being the lowest)')),
                ('distance_from_bit', models.FloatField(help_text='Distance from bit in meters')),
                ('bha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_positions', to='plotter.bha')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotter.bhacomponent')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('bha', 'position')},
            },
        ),
        migrations.AddField(
            model_name='bha',
            name='components',
            field=models.ManyToManyField(through='plotter.BHAComponentPosition', to='plotter.bhacomponent'),
        ),
    ]
