# Generated by Django 5.0.2 on 2025-11-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0025_bhacomponent_bha_bhacomponentposition_bha_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhacomponentposition',
            name='inner_diameter',
            field=models.FloatField(blank=True, help_text='Inner diameter in inches', null=True),
        ),
        migrations.AddField(
            model_name='bhacomponentposition',
            name='length',
            field=models.FloatField(default=1, help_text='Length in meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bhacomponentposition',
            name='outer_diameter',
            field=models.FloatField(default=1, help_text='Outer diameter in inches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bhacomponentposition',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='bhacomponent',
            name='length',
            field=models.FloatField(blank=True, help_text='Length in meters', null=True),
        ),
        migrations.AlterField(
            model_name='bhacomponent',
            name='outer_diameter',
            field=models.FloatField(blank=True, help_text='Outer diameter in inches', null=True),
        ),
    ]
