# Generated by Django 5.0.2 on 2025-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0026_bhacomponentposition_inner_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhacomponent',
            name='inner_diameter',
        ),
        migrations.RemoveField(
            model_name='bhacomponent',
            name='length',
        ),
        migrations.RemoveField(
            model_name='bhacomponent',
            name='outer_diameter',
        ),
        migrations.RemoveField(
            model_name='bhacomponent',
            name='weight',
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='clay_description',
            field=models.CharField(blank=True, help_text='Description of clay type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='coal_description',
            field=models.CharField(blank=True, help_text='Description of coal type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='coal_percentage',
            field=models.FloatField(default=0, help_text='Percentage of coal'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='limestone_description',
            field=models.CharField(blank=True, help_text='Description of limestone type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='limestone_percentage',
            field=models.FloatField(default=0, help_text='Percentage of limestone'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='sand_description',
            field=models.CharField(blank=True, help_text='Description of sand type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='shale_description',
            field=models.CharField(blank=True, help_text='Description of shale type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='slit_description',
            field=models.CharField(blank=True, help_text='Description of slit type', max_length=200, null=True),
        ),
    ]
