# Generated by Django 5.0.2 on 2025-11-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0027_remove_bhacomponent_inner_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationactivity',
            name='image',
            field=models.ImageField(blank=True, help_text='Image related to the operation activity', null=True, upload_to='operation_images/'),
        ),
    ]
