# Generated by Django 5.0.2 on 2025-11-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0028_operationactivity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationactivity',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
