# Generated by Django 5.0.2 on 2025-12-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0029_alter_operationactivity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrillingreport',
            name='gas_show',
            field=models.BooleanField(default=False, help_text='Indicates if any gas show was observed during this report'),
        ),
        migrations.CreateModel(
            name='GasShowMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(help_text='Formation where the gas show was observed', max_length=100)),
                ('depth_m', models.FloatField(help_text='Depth in meters')),
                ('max_percent', models.FloatField(help_text='Maximum gas percentage')),
                ('bg_percent', models.FloatField(help_text='Background gas percentage')),
                ('above_bg_percent', models.FloatField(help_text='Gas percentage above background')),
                ('c1_percent', models.FloatField(help_text='Methane (C1) percentage')),
                ('c2_percent', models.FloatField(help_text='Ethane (C2) percentage')),
                ('c3_percent', models.FloatField(help_text='Propane (C3) percentage')),
                ('ic4_percent', models.FloatField(help_text='Iso-butane (iC4) percentage')),
                ('nc5_percent', models.FloatField(help_text='Normal pentane (nC5) percentage')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes for this gas show entry', null=True)),
                ('drilling_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_show_measurements', to='plotter.dailydrillingreport')),
            ],
            options={
                'verbose_name': 'Gas Show Measurement',
                'verbose_name_plural': 'Gas Show Measurements',
                'ordering': ['drilling_report', 'depth_m'],
            },
        ),
    ]
