# Generated by Django 5.0.2 on 2025-12-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0030_alter_dailydrillingreport_gas_show_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasshowmeasurement',
            options={'ordering': ['drilling_report', 'start_depth_m'], 'verbose_name': 'Gas Show Measurement', 'verbose_name_plural': 'Gas Show Measurements'},
        ),
        migrations.RemoveField(
            model_name='gasshowmeasurement',
            name='depth_m',
        ),
        migrations.AddField(
            model_name='gasshowmeasurement',
            name='end_depth_m',
            field=models.FloatField(default=1, help_text='End depth in meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasshowmeasurement',
            name='start_depth_m',
            field=models.FloatField(default=1, help_text='Start depth in meters'),
            preserve_default=False,
        ),
    ]
