# Generated by Django 5.0.2 on 2025-12-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0031_alter_gasshowmeasurement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellSurveyStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of the station within the survey')),
                ('md', models.FloatField(help_text='Measured depth (m)')),
                ('inclination', models.FloatField(help_text='Inclination in degrees')),
                ('azimuth', models.FloatField(help_text='Azimuth in degrees')),
                ('tvd', models.FloatField(blank=True, help_text='True vertical depth (m)', null=True)),
                ('northing', models.FloatField(blank=True, null=True)),
                ('easting', models.FloatField(blank=True, null=True)),
                ('dogleg_severity', models.FloatField(blank=True, help_text='Dogleg severity (deg/30m)', null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_stations', to='plotter.well')),
            ],
            options={
                'ordering': ['md'],
                'unique_together': {('well', 'md')},
            },
        ),
    ]
