# Generated by Django 5.0.2 on 2025-12-03 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0032_wellsurveystation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_event', models.CharField(choices=[('drilling', 'Drilling'), ('logging', 'Logging'), ('completion', 'Completion'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=255)),
                ('present_formation', models.CharField(blank=True, choices=[('bokabil', 'Bokabil'), ('duptila', 'Duptila'), ('tipam', 'Tipam'), ('bhuvan', 'Bhuvan'), ('other', 'Other')], max_length=255, null=True)),
                ('rop_latest', models.FloatField(help_text='ROP latest in meters per hour')),
                ('mud_weight_latest', models.FloatField(help_text='Mud weight latest in kg/m3')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drilling_stats', to='plotter.well')),
            ],
            options={
                'verbose_name': 'Drilling Stats',
                'verbose_name_plural': 'Drilling Stats',
                'ordering': ['-id'],
            },
        ),
    ]
