# Generated by Django 5.0.2 on 2025-12-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0033_drillingstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellprognosis',
            name='md_depth_end',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured depth end in meters (calculated from TVD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wellprognosis',
            name='md_depth_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured depth start in meters (calculated from TVD)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wellprognosis',
            name='planned_depth_end',
            field=models.DecimalField(decimal_places=2, help_text='Planned end depth tvd in meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wellprognosis',
            name='planned_depth_start',
            field=models.DecimalField(decimal_places=2, help_text='Planned start depth tvd in meters', max_digits=10),
        ),
    ]
