# Generated by Django 5.0.2 on 2025-12-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0034_wellprognosis_md_depth_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillinglithology',
            name='slit_description',
        ),
        migrations.RemoveField(
            model_name='drillinglithology',
            name='slit_percentage',
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='clay_trace',
            field=models.BooleanField(default=False, help_text='Trace of clay'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='coal_trace',
            field=models.BooleanField(default=False, help_text='Trace of coal'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='limestone_trace',
            field=models.BooleanField(default=False, help_text='Trace of limestone'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='sand_trace',
            field=models.BooleanField(default=False, help_text='Trace of sand'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='shale_trace',
            field=models.BooleanField(default=False, help_text='Trace of shale'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='silt_description',
            field=models.CharField(blank=True, help_text='Description of silt type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='silt_percentage',
            field=models.FloatField(default=0, help_text='Percentage of silt'),
        ),
        migrations.AddField(
            model_name='drillinglithology',
            name='silt_trace',
            field=models.BooleanField(default=False, help_text='Trace of silt'),
        ),
        migrations.AddField(
            model_name='wellprognosis',
            name='target_name',
            field=models.CharField(blank=True, help_text='Name of the target depth', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wellprognosis',
            name='lithology',
            field=models.CharField(choices=[('sand', 'sand'), ('lime', 'lime'), ('shale', 'shale'), ('silt', 'silt'), ('dolomite', 'dolomite'), ('coal', 'coal'), ('clay', 'clay'), ('alteration', 'alteration of sand and shale')], help_text='Expected lithology at this depth', max_length=50),
        ),
    ]
